trigger:
- main

pool:
  vmName: Azure Pipelines

variables: 
  buildConfiguration: 'Release'

steps: 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build --configuration $(buildConfiguration)'